name: Update WakaTime Stats Chart

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # allows manual triggering from GitHub UI

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate lang_stats.png
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase --autostash
          git add lang_stats.png
          git add day_wise_stats.png
          git diff --cached --quiet || git commit -m "Update lang_stats.png"
          git push
